### ISSUE TITLE
Exception when version is not specified in requirements.txt

### ISSUE THREAD

**Issue by zerthimon** [blue-yonder/devpi-builder#95]
It would be nice if devpi-builder could install the latest version of requred package, when no version is specified for it ...

```
Traceback (most recent call last):
  File "/usr/local/bin/devpi-builder", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/devpi_builder/cli.py", line 105, in main
    packages = requirements.read(args.requirements)
  File "/usr/local/lib/python2.7/dist-packages/devpi_builder/requirements.py", line 41, in read
    _extract_project_version(requirement) for requirement in pkg_resources.parse_requirements(input_file)
  File "/usr/local/lib/python2.7/dist-packages/devpi_builder/requirements.py", line 27, in _extract_project_version
    raise ValueError('Version specification is missing for "{}".'.format(requirement))
ValueError: Version specification is missing for "websocket-client".
```

**Comment by theMarix** [comment]
This is an interesting suggestion. I have actually had this use-case myself before. But it vanished because we now `pip-compile` all requirements used in our tests.

The tricky part about adding this feature is that I there was a reason why it currently is not allowed. We want to make sure that we don't accidentally build a wrong version. E.g. when automatically building all packages that passed a defined clearance process. So it is essential for use to retain the old behaviour.

If it is possible to get both behaviours without adding too much complexity to the code base that would be great, though.
